{% set name = "aws-sso-lib" %}
{% set version = "1.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aws-sso-lib-{{ version }}.tar.gz
  sha256: 2f4e2d10c85286598bab665d8c64dcf8dd3f958fb87dcc9a51967605cf9761ec

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<4.0
  run:
    - aws-error-utils >=1.0.4,<2.0.0
    - boto3 >=1.20.28,<2.0.0
    - python >=3.6,<4.0

test:
  imports:
    - aws_sso_lib
    - aws_sso_lib.vendored_botocore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/benkehoe/aws-sso-util
  summary: Library to make AWS SSO easier
  license: Apache-2.0
  # aws-sso-lib includes a vendored subset of the botocore 2
  # supporting sso operations, also under the apache 2.0 license.
  license_file:
    - LICENSE
    - LICENSE.vendored_botocore

extra:
  recipe-maintainers:
    - asford
